//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.DVS.Framework.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dvs_event
    {
        public int Id { get; set; }
        public long EventId { get; set; }
        public string EventName { get; set; }
        public string StartDate { get; set; }
        public Nullable<long> SportId { get; set; }
        public string SportName { get; set; }
        public Nullable<long> LeagueId { get; set; }
        public string LeagueName { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string LocationName { get; set; }
        public string Status { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<long> HomeTeamId { get; set; }
        public string HomeTeamName { get; set; }
        public Nullable<long> AwayTeamId { get; set; }
        public string AwayTeamName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> MarketId { get; set; }
        public string MarketName { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public string ProviderName { get; set; }
        public int ProductId { get; set; }
    }
}
