//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.DVS.Framework.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dvs_schedulershistory
    {
        public int Id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartedOn { get; set; }
        public Nullable<System.DateTime> FinishedOn { get; set; }
        public int Type { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ArrivalMessageId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsByError { get; set; }
        public string ErrorMessage { get; set; }
        public string AdditionalInfo { get; set; }
    }
}
