//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.DVS.Framework.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dvs_arrivalmessage
    {
        public int Id { get; set; }
        public string Events { get; set; }
        public string Sports { get; set; }
        public string Leagues { get; set; }
        public string Locations { get; set; }
        public string Markets { get; set; }
        public string Providers { get; set; }
        public string Bets { get; set; }
        public string Statuses { get; set; }
        public string Url { get; set; }
        public int ProductId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsProcessed { get; set; }
        public string PathToXmlFile { get; set; }
        public Nullable<int> EventsCount { get; set; }
        public Nullable<int> SportsCount { get; set; }
        public Nullable<int> LeaguesCount { get; set; }
        public Nullable<int> LocationsCount { get; set; }
        public Nullable<int> MarketsCount { get; set; }
        public Nullable<int> ProvidersCount { get; set; }
        public Nullable<int> BetsCount { get; set; }
        public Nullable<int> StatusesCount { get; set; }
        public string GroupId { get; set; }
    }
}
