//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.DVS.Framework.DataAccess.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gb_dvsstagingEntities : DbContext
    {
        public gb_dvsstagingEntities()
            : base("name=gb_dvsstagingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dvs_arrivalmessage> dvs_arrivalmessage { get; set; }
        public virtual DbSet<dvs_event> dvs_event { get; set; }
        public virtual DbSet<dvs_eventhistory> dvs_eventhistory { get; set; }
        public virtual DbSet<dvs_product> dvs_product { get; set; }
        public virtual DbSet<dvs_producttree> dvs_producttree { get; set; }
        public virtual DbSet<dvs_schedulershistory> dvs_schedulershistory { get; set; }
        public virtual DbSet<dvs_selectiontreeitem> dvs_selectiontreeitem { get; set; }
        public virtual DbSet<val_datatypes> val_datatypes { get; set; }
        public virtual DbSet<val_operator> val_operator { get; set; }
        public virtual DbSet<val_parameter> val_parameter { get; set; }
        public virtual DbSet<val_priority> val_priority { get; set; }
        public virtual DbSet<val_validationresult> val_validationresult { get; set; }
        public virtual DbSet<val_validationrule> val_validationrule { get; set; }
        public virtual DbSet<val_validationsetting> val_validationsetting { get; set; }
    }
}
