//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSports.DVS.Framework.DataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class val_validationrule
    {
        public int Id { get; set; }
        public Nullable<int> ValidationSettingId { get; set; }
        public string PropertyName { get; set; }
        public string PropertyXPath { get; set; }
        public Nullable<int> ParameterId { get; set; }
        public Nullable<int> OperatorId { get; set; }
        public string Value { get; set; }
        public string ValueXPath { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> NumberOfChanges { get; set; }
        public Nullable<int> DataTypeId { get; set; }
        public string RuleName { get; set; }
        public Nullable<bool> IsTime { get; set; }
        public bool IsForAllNodes { get; set; }
    
        public virtual val_operator val_operator { get; set; }
        public virtual val_parameter val_parameter { get; set; }
        public virtual val_validationsetting val_validationsetting { get; set; }
    }
}
